INSERT INTO STUDENT(ROLL_NO,ATTENDANCE,DEPARTMENT,NAME) VALUES(1001,789,'chemistry','anjul mehta');
INSERT INTO STUDENT(ROLL_NO,ATTENDANCE,DEPARTMENT,NAME) VALUES(1002,79,'physics','pranav singh');
INSERT INTO STUDENT(ROLL_NO,ATTENDANCE,DEPARTMENT,NAME) VALUES(1003,795,'english','ankush khanna');
INSERT INTO STUDENT(ROLL_NO,ATTENDANCE,DEPARTMENT,NAME) VALUES(1004,89,'maths','shruti venkatesh');
INSERT INTO STUDENT(ROLL_NO,ATTENDANCE,DEPARTMENT,NAME) VALUES(1005,90,'hindi','sujith nair');